### ISSUE TITLE
Avoid duplicate users

### ISSUE THREAD

**Issue by annu12340** [JithinKS97/dynamic-learning#73]
Currently, the program allows multiple duplicate users with the same username and email id. A filtering system must be built to avoid redundancy of users

**Comment by JithinKS97** [comment]
Thanks @annu12340 for opening the issue. If you can take up the issue yourself, I'm more than happy to help you. 

The signup takes place in the SignUp Component found here
https://github.com/JithinKS97/dynamic-learning/blob/master/imports/ui/pages/Signup.jsx

Prior to signing up, you should call a server side function which will check if among the currently registered users, the input email ID is already present,  then allow the user to signup or show the error message accordingly.

**Comment by JithinKS97** [comment]
@vishnumj10 Are we goid to close this issue?

**Comment by vishnumj10** [comment]
@JithinKS97 Yes
