### ISSUE TITLE
login with github or google is not working

### ISSUE THREAD

**Issue by annu12340** [JithinKS97/dynamic-learning#74]
![Screenshot (1)](https://user-images.githubusercontent.com/43414928/68128110-1dd38480-ff3d-11e9-8557-c124242988dc.png)
The option to signup through GitHub or google is not working

**Comment by JithinKS97** [comment]
I made an observation recently. These authentications are working fine in chromium browser. But not in chrome.

**Comment by JithinKS97** [comment]
@annu12340 I think this issue is solved by a recent commit. Could you please check if it is resolved in your system.

**Comment by JithinKS97** [comment]
Solved with #78
